name: cached

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**

scripts:
  get:
    run: melos exec dart pub get

  generate:
    run: melos run generate:packages && melos run generate:examples

  generate:packages:
    run: melos exec --depends-on="build_runner" --no-private dart run build_runner build  --delete-conflicting-outputs

  generate:examples:
    run: melos exec --depends-on="build_runner" --depends-on="cached" dart run build_runner build  --delete-conflicting-outputs

  test:
    run: melos exec --dir-exists="test" dart test

  test:coverage:
    run: melos exec  -c 1 --fail-fast -- "\$MELOS_ROOT_PATH/scripts/coverage.sh"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      dirExists: test

  analyze:
    run: melos exec dart analyze

  get:fvm:
    run: melos exec fvm dart pub get

  test:fvm:
    run: melos exec --dir-exists="test" dart test

  analyze:fvm:
    run: melos exec fvm dart analyze

  generate:fvm:
    run: melos run generate:packages:fvm && melos run generate:examples:fvm

  generate:packages:fvm:
    run: melos exec --depends-on="build_runner" --no-private fvm dart run build_runner build  --delete-conflicting-outputs

  generate:examples:fvm:
    run: melos exec --depends-on="build_runner" --depends-on="cached" fvm dart run build_runner build  --delete-conflicting-outputs

  upgrade-deps:
    run: melos exec dart pub upgrade
