name: cached_annotation
description: >
  Annotations for the Cached code-generator.
  This package does nothing without Cached.
version: 1.7.1
repository: https://github.com/Iteo/cached
issue_tracker: https://github.com/Iteo/cached/issues
homepage: https://github.com/Iteo/cached
documentation: https://github.com/Iteo/cached/blob/master/packages/cached/README.md

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  linteo: ^1.0.1
