name: persistent_storage_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cached_annotation:
    path: "../../../cached_annotation"
  hive_ce: ^2.10.1
  http: ^0.13.5

dependency_overrides:
  cached_annotation:
    path: "../../../cached_annotation"

dev_dependencies:
  build_runner: ^2.4.6
  cached:
    path: "../../"
  linteo: ^1.0.1
  hive_ce_generator: ^1.9.5
