name: Build

on:
  pull_request:
    branches:
      - master
      - "rc/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dart
        uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: stable

      - name: Install melos
        run: dart pub global activate melos

      - name: Install coverage
        run: dart pub global activate coverage

      - name: Melos Bootstrap
        run: melos bs

      - name: Install dependencies
        run: melos run get

      - name: Run build_runner
        run: melos run generate

      - name: Analyze project source
        run: melos run analyze

      - name: Run tests
        run: melos run test:coverage
